echo Running sim
python main.py -n 99 -Ttx 10 -zeta 0.25 --mode %1
echo Tree...
python plot-tree.py %1
echo Peer trees...
python plot-ptree.py %1
echo Lengths...
python plot-lengths.py %1
echo Ratios...
python plot-ratios.py %1